import 'package:imtixon/models/loginmodel.dart';

import 'models/chatmodel.dart';

List<ChatModel> itemList = [
  ChatModel('Dostim', 'assets/icons/Vector2.png'),
  ChatModel('onam', 'assets/icons/Vector2.png'),
  ChatModel('tanishim', 'assets/icons/Vector2.png'),
  ChatModel('kimdir', 'assets/icons/Vector2.png'),
  ChatModel('bilmiyman', 'assets/icons/Vector2.png'),
  ChatModel('kimdir', 'assets/icons/Vector2.png'),
  ChatModel('Dostim', 'assets/icons/Vector2.png'),
  ChatModel('onam', 'assets/icons/Vector2.png'),
  ChatModel('tanishim', 'assets/icons/Vector2.png'),
  ChatModel('kimdir', 'assets/icons/Vector2.png'),
  ChatModel('bilmiyman', 'assets/icons/Vector2.png'),
  ChatModel('kimdir', 'assets/icons/Vector2.png'),
  ChatModel('Dostim', 'assets/icons/Vector2.png'),
  ChatModel('onam', 'assets/icons/Vector2.png'),
  ChatModel('tanishim', 'assets/icons/Vector2.png'),
  ChatModel('kimdir', 'assets/icons/Vector2.png'),
  ChatModel('bilmiyman', 'assets/icons/Vector2.png'),
  ChatModel('kimdir', 'assets/icons/Vector2.png'),
  ChatModel('Dostim', 'assets/icons/Vector2.png'),
  ChatModel('onam', 'assets/icons/Vector2.png'),
  ChatModel('tanishim', 'assets/icons/Vector2.png'),
  ChatModel('kimdir', 'assets/icons/Vector2.png'),
  ChatModel('bilmiyman', 'assets/icons/Vector2.png'),
  ChatModel('kimdir', 'assets/icons/Vector2.png'),
  ChatModel('Dostim', 'assets/icons/Vector2.png'),
  ChatModel('onam', 'assets/icons/Vector2.png'),
  ChatModel('tanishim', 'assets/icons/Vector2.png'),
  ChatModel('kimdir', 'assets/icons/Vector2.png'),
  ChatModel('bilmiyman', 'assets/icons/Vector2.png'),
  ChatModel('kimdir', 'assets/icons/Vector2.png'),
  ChatModel('Dostim', 'assets/icons/Vector2.png'),
  ChatModel('onam', 'assets/icons/Vector2.png'),
  ChatModel('tanishim', 'assets/icons/Vector2.png'),
  ChatModel('kimdir', 'assets/icons/Vector2.png'),
  ChatModel('bilmiyman', 'assets/icons/Vector2.png'),
];
